[config]
reload_apps = true
set_wallpaper = false

[config.reload_apps_list]
gtk = true

[templates.gtk3]
input_path = '~/.config/matugen/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.p10k]
input_path = '~/.config/matugen/p10k.zsh'
output_path = '~/.p10k.zsh'

[templates.foot]
input_path = '~/.config/matugen/foot.ini'
output_path = '~/.config/foot/foot.ini'

[templates.bat]
input_path = '~/.config/matugen/material3.tmTheme'
output_path = '~/.config/bat/themes/Material3.tmTheme'
